<?php
$res = array(
'Insert_FH' => 'Insertar',
'Update_FH' => 'Actualizar',
'Record_FH' => 'Guardar',
'Insert_FB' => 'Insertar',
'Update_FB' => 'Actualizar',
'Delete_FB' => 'Borrar',
'Cancel_FB' => 'Cancelar',
'Insert as new_FB' => 'Insertar como nuevo',
'Select one...' => 'Seleccione uno...',
'Are you sure?' => '&iquest;Est&aacute;s seguro?',
'Filter' => 'Filtrar',
'Show' => 'Mostrar',
'all' => 'todo',
'records' => 'registros',
'Reset filter' => 'Limpiar filtro',
'Show filter' => 'Mostrar filtro',
'Order' => 'Ordenar',
'save' => 'guardar',
'None' => 'Ninguno',
'The table is empty or the filter you\'ve selected is too restrictive.' => 'La tabla est&aacute; vac&iacute;a o el filtro seleccionado es muy restrictivo.',
'edit_one' => 'editar',
'delete_one' => 'borrar',
'edit_all' => 'editar',
'delete_all' => 'borrar',
'add new' => 'a&ntilde;adir nuevo',
'ARE_YOU_SURE_MOVE' => 'Ha cambiado el orden de algunos datos y no se pudieron guardar los cambios. Si continúa, perderá los cambios.',
'ARE_YOU_SURE_DELETE' => '¿Está seguro que quiere borrar estos registros?',
'PLEASE_SELECT_RECORD' => 'Por favor seleccione al menos un registro.',
'to' => 'al',
'of' => 'de',
'First' => 'Primero',
'Previous' => 'Anterior',
'Next' => 'Siguiente',
'Last' => '&Uacute;ltimo',
);
?>